### ISSUE TITLE
Release SNOW on PROD

### ISSUE THREAD

**Issue by michamos** [cern-sis/issues-inspire#362]
There are many places in the UI where we tell people to write to `...@inspirehep.net`. With the SNow transition, we are removing those support channels and will instead have a help page at https://help.inspirehep.net/knowledge-base/contact-us (doesn't exist yet). The UI need to be updated to refer to that page instead.

For example, `contact us at authors@inspirehep.net` becomes
```
<a href="https://help.inspirehep.net/knowledge-base/contact-us">contact us</a>
```

**Comment by drjova** [comment]
What needs to be done:

- [ ] create/publish [page](https://help.inspirehep.net/knowledge-base/contact-us) in wordpress
- [ ] merge https://github.com/inspirehep/inspirehep/pull/3025
- [ ] set the [feature flag](https://github.com/cern-sis/kubernetes/blob/346e7bc50b79722252ef0a77f3bc679a939e5acf/hep/environments/inspire-prod/kustomization.yml#L115) to True
- [ ] Remove [this hack](https://github.com/inspirehep/inspirehep/blob/11cd40802ee3477750a280fc2a4688842a8d5221/backend/inspirehep/submissions/tasks.py#L24)
