### ISSUE TITLE
backoffice: API checklist 

### ISSUE THREAD

**Issue by pamfilos** [cern-sis/issues-inspire#470]
- Search page
  - [ ] List workflows
     - [x] pagination
     - [x] sorting
     - [ ] limit
  - [ ] Search:
     - [ ] with query (text, ids, etc)
     - [x] by status
     - [x] other aggs
- Workflow/Detail page
  - [ ] CRUD
  - [x] Fetch workflow detailed data
  - [x] Fetch author/record detailed data
  - [ ] Fetch workflow error
  - [ ] Fetch workflow related tickets
  - [ ] Fetch author related tickets
  - [x] 'Approve', 'Reject' curation actions
  - [x] Workflow actions: `restart`, `next step`, `restart current`, `restart with params`
  
UI:
(1)
![Screenshot-2024-05-22-at-10 54 10](https://github.com/cern-sis/issues-inspire/assets/6625469/d40de28f-dc27-4093-bb27-28cb07ac08fb)

(2)
![localhost_3000_holdingpen_author_123456-1](https://github.com/cern-sis/issues-inspire/assets/6625469/6d4396f3-6e1d-4d8f-a636-e4612811d139)

**Comment by karolina-siemieniuk-morawska** [comment]
For completed workflows we also need an indication that it's completed the decision (like 'Accepted with Curation')
![Screenshot 2024-05-28 at 10 04 14](https://github.com/cern-sis/issues-inspire/assets/55505399/8197a4f7-7d18-46d2-89a7-7e224dd24cee)

**Comment by DonHaul** [comment]
Current progress

- Search page
- [ ]   List workflows
  - [x]  pagination - just implemented in backoffice
  - [ ]  sorting
  - [ ]  limit - ?
- [ ]  Search:
  - [ ]  with query (text, ids, etc)
  - [ ]  by status
  - [ ]  other aggs

- Workflow/Detail page

- [x]  CRUD - in backoffice
- [x]  Fetch workflow detailed data - in backoffice
- [ ]  Fetch author/record detailed data - ()
- [ ]  Fetch workflow error
- [ ]  Fetch workflow related tickets
- [ ]  Fetch author related tickets
- [x]  'Approve', 'Reject' curation actions - in backoffice
- [ ]  Workflow actions: `restart`, `next step`, `restart current`, `restart with params`

**Comment by karolina-siemieniuk-morawska** [comment]
List of missing api with new structure:

- Decision: 

![Image](https://github.com/user-attachments/assets/cf5a71bc-fe38-4c5f-8363-a5264eafe19f)
![Image](https://github.com/user-attachments/assets/fa8d36fb-0bef-438c-a34b-b5f9f4b828e4)
```
    {
         "user_action": "accept_curate” | “accept” | “reject”
    }
```

- Snow ticket:

![Image](https://github.com/user-attachments/assets/65754351-715c-4641-8d69-536574517f68)
```
    {
         “ticket”t_id: “”, 
         “ticket_url”: “”
    }
```

- Error: 

![Image](https://github.com/user-attachments/assets/cd5190b0-9cd1-4a86-be99-1b1a1ccb6196)

```
    {
         “_error_msg”: “”
    }
```

- Decision status: (“_message” || “_last_task_name”)

![Image](https://github.com/user-attachments/assets/adef67b0-e5ba-4d01-89e9-f016ab5fdb14)

```
    {
         “_message” || “_last_task_name”: “”
    }
```


I provided how it was in the previous data structure and how frontend currently expects it, if you decide to change structure let me know so I can handle it on ui.
