### ISSUE TITLE
Missing fields from the backoffice

### ISSUE THREAD

**Issue by drjova** [cern-sis/issues-inspire#513]
List of missing api with new structure:

- Decision: 

![Image](https://github.com/user-attachments/assets/cf5a71bc-fe38-4c5f-8363-a5264eafe19f)
![Image](https://github.com/user-attachments/assets/fa8d36fb-0bef-438c-a34b-b5f9f4b828e4)
```
    {
         "user_action": "accept_curate” | “accept” | “reject”
    }
```

- Snow ticket:

![Image](https://github.com/user-attachments/assets/65754351-715c-4641-8d69-536574517f68)
```
    {
         “ticket”t_id: “”, 
         “ticket_url”: “”
    }
```

- Error: 

![Image](https://github.com/user-attachments/assets/cd5190b0-9cd1-4a86-be99-1b1a1ccb6196)

```
    {
         “_error_msg”: “”
    }
```

- Decision status: (“_message” || “_last_task_name”)

![Image](https://github.com/user-attachments/assets/adef67b0-e5ba-4d01-89e9-f016ab5fdb14)

```
    {
         “_message” || “_last_task_name”: “”
    }
```

I provided how it was in the previous data structure and how frontend currently expects it, if you decide to change structure let me know so I can handle it on ui.  

### Tasks

- [ ] https://github.com/cern-sis/issues-inspire/issues/522
- [ ] https://github.com/cern-sis/issues-inspire/issues/518
- [ ] https://github.com/cern-sis/issues-inspire/issues/519
- [ ] https://github.com/cern-sis/issues-inspire/issues/520

**Comment by drjova** [comment]
Decision

- Probably we need another table to keep track of the actions

SNOW ticket:
We already have the model https://github.com/inspirehep/backoffice/blob/main/backoffice/backoffice/workflows/models.py#L36 we need to include it in the serializer and add an atrribute for ticket_url

Errors:
We just need to find a way to generate a URL to airflow with the errored task
